### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Raid-Raky** [Raid-Gaming/Deathrun#1]
My anal plug is stuck in my ass. How to get it out?

**Comment by MichaelHillcox** [comment]
Soldering Iron

**Comment by StefanVII** [comment]
Have you tried turning it on and off again?

If that doesn't work check to make sure you have the latest graphics and DirectX drivers installed.

**Comment by Raid-Raky** [comment]
I have installed lastest graphics and DirectX drivers and it came out, but something else with it came out. Its some kind of brown warm stuff, smelling very funny. Can I eat it?
